server:
  port: 9000
spring:
  application:
    # 应用名称
    name: spring-gateway
  cloud:
    # 使用 Naoos 作为服务注册发现
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 使用 Sentinel 作为熔断器
#    sentinel:
#      transport:
#        port: 8721
#        dashboard: localhost:8080
    # 路由网关配置
    gateway:
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      # 配置路由规则
      routes:
        - id: service-consumer
          uri: lb://service-consumer
          predicates:
            - Path=/consumer/**
            - Method=GET
          filters:
            - StripPrefix=1

        - id: service-provider
          uri: lb://service-provider
          predicates:
            - Path=/provider/**
            - Method=GET
          filters:
            - StripPrefix=1


# 目前无效
feign:
  sentinel:
    enabled: true

# 目前无效
management:
  endpoints:
    web:
      exposure:
        include: "*"
